name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16'

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

      # Check if the dist directory exists
      - name: Check dist directory
        run: |
          if [ -d "dist" ]; then
            echo "dist directory exists."
            
          else
            ls -la  # List all files in the current directory
            echo "dist directory does not exist."
            exit 1
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Echo NETLIFY_SITE_ID
        run: echo ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify login 
          
          netlify link --id 27fc336a-a42d-4621-a616-fda30f97aebd
          netlify build
          netlify deploy --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
