name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16'

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Echo NETLIFY_SITE_ID
        run: echo ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify login
          
          netlify link --id ${{ secrets.NETLIFY_SITE_ID }}
          netlify deploy --dir=dist --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
