name: CI/CD Pipeline

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16.16'

      - name: Cache node modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install dependencies
        run: npm install

      - name: Build Vite app
        run: npm run build

  find-dist:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Find dist directory
        run: |
          dist_path=$(find . -type d -name "dist" -print -quit)
          echo "Found dist directory at: $dist_path"
        shell: bash

  deploy:
    needs: find-dist
    runs-on: ubuntu-latest

    steps:
      - name: Echo NETLIFY_SITE_ID
        run: echo ${{ secrets.NETLIFY_SITE_ID }}

      - name: Deploy to Netlify
        run: |
          npm install -g netlify-cli
          netlify login
          
          netlify link --id 27fc336a-a42d-4621-a616-fda30f97aebd
          netlify deploy --dir=/mern-final-project-frontend --prod
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
